/**
 * Seed assets table.
 *
 * @param   {object} knex
 * @returns {Promise}
 */
exports.seed = function (knex) {
    return knex('assets').del().then(function () {
        return knex('assets').insert([
            {
                id: 1,
                asset_code: 'CNTT-001',
                name: 'Laptop Dell Latitude 5420',
                asset_type_id: 1,
                serial_number: 'DL5420-SN001',
                description: 'Laptop văn phòng phòng CNTT',
                purchase_date: '2023-01-15',
                start_use_date: '2023-01-20',
                status: 'IN_USE',
                location_id: 2,
                warranty_expiry: '2026-01-15',
                supplier: 'Dell Vietnam',
            },
            {
                id: 2,
                asset_code: 'CNTT-002',
                name: 'Máy tính để bàn HP ProDesk 400',
                asset_type_id: 1,
                serial_number: 'HP400-SN002',
                description: 'Máy tính bàn phòng kế toán',
                purchase_date: '2022-06-10',
                start_use_date: '2022-06-15',
                status: 'IN_USE',
                location_id: 1,
                warranty_expiry: '2025-06-10',
                supplier: 'HP Vietnam',
            },
            {
                id: 3,
                asset_code: 'CNTT-003',
                name: 'Màn hình Samsung 24 inch',
                asset_type_id: 3,
                serial_number: 'SAM24-SN003',
                description: 'Màn hình phòng kinh doanh',
                purchase_date: '2023-03-01',
                start_use_date: '2023-03-05',
                status: 'IN_USE',
                location_id: 4,
                warranty_expiry: '2026-03-01',
                supplier: 'Samsung Vietnam',
            },
            {
                id: 4,
                asset_code: 'VP-001',
                name: 'Máy in Canon LBP 2900',
                asset_type_id: 2,
                serial_number: 'CLB2900-SN004',
                description: 'Máy in văn phòng tầng 1',
                purchase_date: '2021-09-20',
                start_use_date: '2021-09-25',
                status: 'IN_REPAIR',
                location_id: 1,
                warranty_expiry: '2024-09-20',
                supplier: 'Canon Vietnam',
            },
            {
                id: 5,
                asset_code: 'VP-002',
                name: 'Máy photo Toshiba e-STUDIO 2528A',
                asset_type_id: 2,
                serial_number: 'TSH2528-SN005',
                description: 'Máy photo hành chính',
                purchase_date: '2022-11-01',
                start_use_date: '2022-11-10',
                status: 'IN_USE',
                location_id: 3,
                warranty_expiry: '2025-11-01',
                supplier: 'Toshiba Vietnam',
            },
            {
                id: 6,
                asset_code: 'DL-001',
                name: 'Điều hòa Daikin 12000 BTU',
                asset_type_id: 6,
                serial_number: 'DAI12K-SN006',
                description: 'Điều hòa phòng máy chủ',
                purchase_date: '2020-05-15',
                start_use_date: '2020-06-01',
                status: 'IN_USE',
                location_id: 6,
                warranty_expiry: '2023-05-15',
                supplier: 'Daikin Vietnam',
            },
            {
                id: 7,
                asset_code: 'CNTT-004',
                name: 'Server Dell PowerEdge T340',
                asset_type_id: 1,
                serial_number: 'DPET340-SN007',
                description: 'Máy chủ ứng dụng nội bộ',
                purchase_date: '2021-02-28',
                start_use_date: '2021-03-01',
                status: 'IN_USE',
                location_id: 6,
                warranty_expiry: '2024-02-28',
                supplier: 'Dell Vietnam',
            },
            {
                id: 8,
                asset_code: 'CNTT-005',
                name: 'Laptop Lenovo ThinkPad E14',
                asset_type_id: 1,
                serial_number: 'LTPE14-SN008',
                description: 'Laptop phòng kỹ thuật',
                purchase_date: '2024-01-10',
                start_use_date: '2024-01-15',
                status: 'NEW',
                location_id: 2,
                warranty_expiry: '2027-01-10',
                supplier: 'Lenovo Vietnam',
            },
            {
                id: 9,
                asset_code: 'VP-003',
                name: 'Bàn họp 10 chỗ',
                asset_type_id: 4,
                serial_number: null,
                description: 'Bàn họp phòng hội nghị tầng 2',
                purchase_date: '2020-08-01',
                start_use_date: '2020-08-10',
                status: 'IN_USE',
                location_id: 2,
                warranty_expiry: null,
                supplier: 'Hòa Phát',
            },
            {
                id: 10,
                asset_code: 'NN-001',
                name: 'Switch Cisco Catalyst 2960',
                asset_type_id: 3,
                serial_number: 'CSC2960-SN010',
                description: 'Switch mạng nội bộ tầng 1',
                purchase_date: '2021-07-20',
                start_use_date: '2021-07-22',
                status: 'IN_USE',
                location_id: 6,
                warranty_expiry: '2024-07-20',
                supplier: 'Cisco Vietnam',
            },
        ]);
    });
};
