/**
 * Seed employees table.
 *
 * @param   {object} knex
 * @returns {Promise}
 */
exports.seed = function (knex) {
    return knex('employees').del().then(function () {
        return knex('employees').insert([
            {
                id: 1,
                employee_code: 'NV-001',
                full_name: 'Nguyễn Văn An',
                email: 'an.nguyen@company.vn',
                phone: '0901234567',
                gender: 'male',
                date_of_birth: '1985-03-15',
                department_id: 1,
                position: 'Giám đốc',
                job_title: 'Giám đốc điều hành',
                manager_id: null,
                employment_status: 'official',
                probation_date: '2010-01-01',
                official_date: '2010-04-01',
                address: '12 Nguyễn Huệ, Q1, TP.HCM',
            },
            {
                id: 2,
                employee_code: 'NV-002',
                full_name: 'Trần Thị Bích',
                email: 'bich.tran@company.vn',
                phone: '0912345678',
                gender: 'female',
                date_of_birth: '1990-07-22',
                department_id: 2,
                position: 'Trưởng phòng',
                job_title: 'Trưởng phòng CNTT',
                manager_id: 1,
                employment_status: 'official',
                probation_date: '2015-06-01',
                official_date: '2015-09-01',
                address: '45 Lê Lợi, Q3, TP.HCM',
            },
            {
                id: 3,
                employee_code: 'NV-003',
                full_name: 'Lê Minh Cường',
                email: 'cuong.le@company.vn',
                phone: '0923456789',
                gender: 'male',
                date_of_birth: '1993-11-08',
                department_id: 2,
                position: 'Nhân viên',
                job_title: 'Kỹ sư hệ thống',
                manager_id: 2,
                employment_status: 'official',
                probation_date: '2019-03-01',
                official_date: '2019-06-01',
                address: '78 Hai Bà Trưng, Q1, TP.HCM',
            },
            {
                id: 4,
                employee_code: 'NV-004',
                full_name: 'Phạm Thị Dung',
                email: 'dung.pham@company.vn',
                phone: '0934567890',
                gender: 'female',
                date_of_birth: '1988-05-30',
                department_id: 3,
                position: 'Trưởng phòng',
                job_title: 'Trưởng phòng Kế toán',
                manager_id: 1,
                employment_status: 'official',
                probation_date: '2013-02-01',
                official_date: '2013-05-01',
                address: '99 Đinh Tiên Hoàng, BT, TP.HCM',
            },
            {
                id: 5,
                employee_code: 'NV-005',
                full_name: 'Hoàng Văn Em',
                email: 'em.hoang@company.vn',
                phone: '0945678901',
                gender: 'male',
                date_of_birth: '1995-09-14',
                department_id: 4,
                position: 'Nhân viên',
                job_title: 'Nhân viên Hành chính',
                manager_id: 1,
                employment_status: 'official',
                probation_date: '2020-08-01',
                official_date: '2020-11-01',
                address: '23 Võ Thị Sáu, Q3, TP.HCM',
            },
            {
                id: 6,
                employee_code: 'NV-006',
                full_name: 'Vũ Thị Phương',
                email: 'phuong.vu@company.vn',
                phone: '0956789012',
                gender: 'female',
                date_of_birth: '1992-12-05',
                department_id: 5,
                position: 'Nhân viên',
                job_title: 'Nhân viên Kinh doanh',
                manager_id: 1,
                employment_status: 'official',
                probation_date: '2018-01-15',
                official_date: '2018-04-15',
                address: '56 Cách Mạng Tháng 8, Q10, TP.HCM',
            },
            {
                id: 7,
                employee_code: 'NV-007',
                full_name: 'Đặng Quốc Giang',
                email: 'giang.dang@company.vn',
                phone: '0967890123',
                gender: 'male',
                date_of_birth: '1991-04-18',
                department_id: 6,
                position: 'Trưởng phòng',
                job_title: 'Trưởng phòng Kỹ thuật',
                manager_id: 1,
                employment_status: 'official',
                probation_date: '2016-10-01',
                official_date: '2017-01-01',
                address: '34 Pasteur, Q1, TP.HCM',
            },
            {
                id: 8,
                employee_code: 'NV-008',
                full_name: 'Bùi Thị Hoa',
                email: 'hoa.bui@company.vn',
                phone: '0978901234',
                gender: 'female',
                date_of_birth: '1997-02-28',
                department_id: 2,
                position: 'Nhân viên',
                job_title: 'Lập trình viên',
                manager_id: 2,
                employment_status: 'probation',
                probation_date: '2026-01-10',
                official_date: null,
                address: '10 Nguyễn Đình Chiểu, Q3, TP.HCM',
            },
        ]);
    });
};
