export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const ENTITY_FAILURE = 'ENTITY_FAILURE';
export const ENTITY_CREATE = 'ENTITY_CREATE';
export const ENTITY_UPDATE = 'ENTITY_UPDATE';
export const ENTITY_FETCH = 'ENTITY_FETCH';
export const ENTITY_DELETE = 'ENTITY_DELETE';
export const SELECT_ENTITY_ITEM = 'SELECT_ENTITY_ITEM';
export const CLEAR_ENTITY_LIST = 'CLEAR_ENTITY_LIST';

export const REPAIR_REQUEST_SEARCH_SUCCESS = 'REPAIR_REQUEST_SEARCH_SUCCESS';
export const REPAIR_REQUEST_FETCH_BY_ID_SUCCESS = 'REPAIR_REQUEST_FETCH_BY_ID_SUCCESS';
export const REPAIR_REQUEST_SET_SELECTED_IDS = 'REPAIR_REQUEST_SET_SELECTED_IDS';
export const REPAIR_REQUEST_SET_MODAL_MODE = 'REPAIR_REQUEST_SET_MODAL_MODE';
export const REPAIR_REQUEST_UPDATE_STATUS_SUCCESS = 'REPAIR_REQUEST_UPDATE_STATUS_SUCCESS';
export const REPAIR_REQUEST_FAILURE = 'REPAIR_REQUEST_FAILURE';
export const REPAIR_REQUEST_CLEAR_ERROR = 'REPAIR_REQUEST_CLEAR_ERROR';
export const REPAIR_REQUEST_SET_LOADING = 'REPAIR_REQUEST_SET_LOADING';
export const REPAIR_REQUEST_SET_SUCCESS = 'REPAIR_REQUEST_SET_SUCCESS';